name: TDR Wait Time Auto-Fetcher

on:
  schedule:
    # 日本時間の 09:00, 09:30 ... 21:00, 21:30 に実行
    # UTCでは 00:00, 00:30 ... 12:00, 12:30
    - cron: '0,30 0-12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Fetch Script
        run: node index.js

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Action-bot'
          git config --global user.email 'action@github.com'
          # 【重要】ここを tdr_status.json に変更
          git add tdr_status.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update wait times" && git push)